### ISSUE TITLE
Any way to support environment variables?

### ISSUE THREAD

**Issue by thunderz99** [fwcd/kotlin-debug-adapter#39]
## Problem

Seems there is no way to pass environment variables to the kotlin-debug-adapter.
I need to pass database connection strings by environment variables in my project.

## To reproduce

Clone the kotlin-quick-start repo. Add the following line to Main.kt.

```kotlin
fun main(args: Array<String>) {

        // added to test environment variables
	println("""System.getenv("MESSAGE"): ${System.getenv("MESSAGE")} """)
	println("Hello world")
}
```

Use ```./gradlew run``` you can get the environment variables(MESSAGE=test)

```
% export MESSAGE="test" && ./gradlew run

> Task :run
System.getenv("MESSAGE"): test 
Hello world

BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 executed
```

Use Kotlin Launch, I cannot get the environment variables.

```
[INFO] main      Connected to client
[INFO] async1    Resolving dependencies for 'kotlin-quick-start' through Gradle's CLI...
[INFO] async1    Creating temporary gradle file /var/folders/51/7dvp_d0969z9v2y05l6knplc0000gn/T/classpath14115259569083174887.gradle
[INFO] async1    Successfully resolved dependencies using Gradle dependencies CLI
[INFO] async1    Starting JVM debug session with main class MainKt
System.getenv("MESSAGE"): null 
Hello world
[INFO] eventBus  Sent exit event
[INFO] async0    Exiting JDI session
``

I tried to add a "env" property to launch.json but there is no luck.
![image](https://user-images.githubusercontent.com/2606944/85646656-85f6f680-b6d7-11ea-8f85-baf652587142.png)


## Appendix

launch.json

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "kotlin",
            "request": "launch",
            "name": "Kotlin Launch",
            "projectRoot": "${workspaceFolder}",
            "mainClass": "MainKt",
            "preLaunchTask": "build"
        }
    ]
}
```

tasks.json

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "./gradlew build -x test",
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

**Comment by fwcd** [comment]
The debug adapter currently does not support this. To support custom environment variables, we might have to start the debuggee process externally and connect the debug adapter to it through a socket. This is, at least, what the Java extension does: https://github.com/microsoft/java-debug/pull/89

**Comment by zhlei2020** [comment]
Thanks for the reply!  I'll have a try on the attach mode.

**Comment by thunderz99** [comment]
Thanks for the reply. I'll have a try on the "attach" mode.

**Comment by thunderz99** [comment]
> "request": "attach" configuration

I tried the attach configuration, unfortunately it didn't work.

## To reproduce

```shell

% cd kotlin-quick-start

./gradlew run --debug-jvm

> Task :run
Listening for transport dt_socket at address: 5005

```

Run the Kotlin Attach config in vscode. But got Exception below:
I double checked the "port" config in the launch.json, and seems the config is correct.


```
[INFO] main      Connected to client
[ERROR] async0    Internal error: org.javacs.ktda.util.KotlinDAException: Sent attach to debug adapter without the required argument'port'
[ERROR] java.util.concurrent.CompletionException: org.javacs.ktda.util.KotlinDAException: Sent attach to debug adapter without the required argument'port'
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1803)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:832)
[ERROR] Caused by: org.javacs.ktda.util.KotlinDAException: Sent attach to debug adapter without the required argument'port'
[ERROR] 	at org.javacs.ktda.adapter.KotlinDebugAdapter.missingRequestArgument(KotlinDebugAdapter.kt:116)
...
```

My launch.json is: 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "kotlin",
            "request": "attach",
            "name": "Kotlin Attach",
            "projectRoot": "${workspaceFolder}",
            "hostName": "localhost",
            "port": 5005,
            "timeout": 30000
        },
        {
            "type": "kotlin",
            "request": "launch",
            "name": "Kotlin Launch",
            "projectRoot": "${workspaceFolder}",
            "mainClass": "MainKt",
            "preLaunchTask": "build"
        },
        {
            "type": "java",
            "name": "Java Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 5005
        }
    ]
}

```

The Java Debug(Attach) works. It correctly attached and showed call stack. (Of cause it doesn't recognize kotlin breakpoints though.)

**Comment by thunderz99** [comment]
It worked when I build the kotlin-debug-adapter locally. Maybe the one in the latest-release is out of date.
Anyway thank you for your advice!
